%TEST_FAST Script for running about 70 min. of tests covering most
% of the functionalities of the package 
%
%  Description
%    Run selected tests in xunit folder. Each of the test functions
%    runs corresponding demo and compares the values to previously saved
%    ones for errors. This is useful e.g. in case user modifies functions
%    provided by GPstuff.
%
%  See also
%    Readme.txt
%
% Copyright (c) 2011-2012 Ville Tolvanen, Tuomas Sivula

% This software is distributed under the GNU General Public 
% License (version 3 or later); please refer to the file 
% License.txt, included with the software, for details.

% Define the test to run
tests = {'test_binomial1', ...
'test_binomial_apc', ...
'test_classific', ...
'test_derivativeobs', ...
'test_hierprior', ...
'test_hurdle', ...
'test_improvemarginals', ...
'test_kalman1', ...
'test_kalman2', ...
'test_lgcp', ...
'test_loopred', ...
'test_memorysave', ...
'test_modelassesment1', ...
'test_monotonic2', ...
'test_multiclass_nested_ep', ...
'test_multinom', ...
'test_neuralnetcov', ...
'test_periodic', ...
'test_quantilegp', ...
'test_regression1', ...
'test_regression_additive1', ...
'test_regression_additive2', ...
'test_regression_hier', ...
'test_regression_meanf', ...
'test_regression_robust', ...
'test_regression_sparse1', ...
'test_regression_sparse2', ...
'test_spatial1', ...
'test_survival_aft', ...
'test_survival_coxph', ...
'test_zinegbin'}';

% Remove previous test values and create empty folder for new test values.
path = which('test_all.m');
path = strrep(path, 'test_all.m', 'testValues');
if exist(path,'dir') == 7
    rmdir(path, 's');
end
mkdir(path);

% Create TestSuite object suite which includes selected tests and logger
% object which keeps track of the number of tests, failures and
% errors. Run tests and print logger information. Can be run from any
% directory.

path2 = cd;
cd(strrep(path,'testValues', ''));
suite = TestSuite;
for i = 1:length(tests)
  suite.add(TestSuite(tests{i}));
end

logger = TestRunLogger;
suite.run(logger);
cd(path2);

logger
